### PR TITLE
Add support for building against system libraries of libserialport an…

### LINKED ISSUE #35: Allow building with system installed libraries
blisp uses few submodules (libserialport, argtable). Many distributions already package those. Likely, blips does not plan any custom patches in those.

It would be convenient enhancement to allow -- at least optionally (CMake define) -- using any prepackaged system libraries, using e.g. cmake/pkgconfig mechanisms to check for existence of required version. Providing this may ease source based distribution, and may also benefit previous topics like issue #5 or issue #32 .

### PR DESCRIPTION
**Pull request by schdro**
Allow building against existing system libraries of libserialport and argtable.
By default (new variable unset), still prepackages vendor libraries should be used for build.

Proposal to fix created issue:
Resolves #35

### CODE REVIEW

**Comment by Ralim** [comment]
@schdro If you can rebase this I'm happy for this to go in :)

**Comment by schdro** [comment]
Hmm, rebase seems to break PR (pulling in old commits), closing for now.

**Comment by Ralim** [comment]
Damn sorry; if you can get it working I would be keen to add it.

Would be ideal to also build with system libs in ci if we can, to try and make sure it works.

**Comment by schdro** [comment]
ok, understood
When time permits, will try to create new fbranch/PR from scratch.

For Ubuntu (CI) unsure if they already have syslibs in place. Might then mean to somehow install other packages first.

The change certainly is interesting, because should allow to build e.g. for source based dists, where binaries and submodule downloads by the build are undesired (e.g. Gentoo sandbox by default disables unmanaged build downloads). Using it here as local Gentoo ebuild, sys-apps/blisp + dev-libs/argtable-3.2.2 + dev-libs/libserialport. ArchLinux might be similar.

**Pull request closed without merging**
