### PR TITLE
Instructions for Linux build from source code, Pinecil V2 Flashing, and Troubleshooting

### PR DESCRIPTION
**Pull request by River-b**
Added the Following:

1.  Instructons to make a Linux build from source code
2. eflash folder with needed eflash**.bin
3. Pinecil V2 flashing instructions
4. Troubleshooting section
5. Links to Pinecil Wiki and Github IronOS.

### CODE REVIEW

**Comment by NovaViper** [comment]
Hey I just noticed the link to the bin file doesn't work (https://github.com/blisp/tree/master/eflash)

**Comment by River-b** [comment]
> Hey I just noticed the link to the bin file doesn't work (https://github.com/blisp/tree/master/eflash)

1. It is there but this is a PR, means that it's still in My Fork and not in this  Repo  yet.   @gamelaster   has to accept my PR update and only then it will appear in this main Repo.
2. for now you have to go to my fork to get it . https://github.com/River-b/blisp
3.  you don't even need to build your own Linux any more.  you can get it inside Discord, go to Pinecil Channel,  in Pins at top of that channel. Since you are a Discord member, this is much easier.   in Discord there is a fully made Linux  executable that includes the eflash and should work on all Linux versions.   All you do is download it from Discord pins,  put in same folder the Pinecilv2_EN.bin  and then   execute it.

**Comment by River-b** [comment]
@robertlipe  technically we are inside  a Pull Request that hasn't been accepted by owner yet.  I made my links so they would not break when accepted into the Main repo and not refer back to my own repo.  
did not think people would be building this from scratch  anymore since we have a Linux blisp flasher executable Zip file now with   the eflash and everything,  downloadable in Discord chat.  
I thought these instructions would be accepted into the  Repo by now.   so people coming in here to read my "PR"  is like a work around as it is to get to these instructions. 
   Since the Issue ticket  is closed,  they have to come here to read these "beta"  instructions.  which is better than having no instructions or  me needing to retype all of this since it already is here. 
Once this PR is accepted.  this problem will go away.

**Comment by River-b** [comment]
> It's unfortunate the PR was closed without actually being fixed.

I don't think my PR for blisp  has been closed, It is still open in main blisp of gamiee, just waiting for approval.  if you need the eflash file and don't want to grab it from discord Pinecil chat Pins at top.  you can just go to my fork  here https://github.com/River-b/blisp/tree/master/eflash
and I  sent it to you  in Discord also. 

if you jumped over to River's blisp then you will not see any PR.

**Pull request merged**
